name: Reusable Workflow
on:
  workflow_call:
    inputs:
      image_flavors:
        description: "JSON string of flavors to build, '[main, nvidia-open]'"
        default: "['main','nvidia-open']"
        type: string
      image_names:
        description: "JSON string of Image Name: '[aurora, aurora-dx]"
        required: true
        default: aurora
        type: string
      stream_name:
        description: "The Fedora Version: stable, or latest"
        required: true
        type: string
      architectures:
        description: "JSON string of architectures to build: '[amd64, arm64]'"
        default: '["amd64"]'
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}-${{ inputs.image_names }}-${{ inputs.stream_name }}
  cancel-in-progress: true

jobs:
  build_container:
    name: ${{ matrix.group }} (${{ matrix.architecture }})
    strategy:
      fail-fast: false
      matrix:
        include:
          - group: aurora
            arch: [amd64, arm64]
          - group: aurora-dx
            arch: [amd64, arm64]
          - group: aurora-dx-nvidia-open
            arch: [amd64, arm64]
          - group: aurora-nvidia-open
            arch: [amd64, arm64]
    runs-on: ${{ matrix.include.arch == 'amd64' && 'ubuntu-26.04' || 'ubuntu-26.04-arm' }}
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Image Name
        shell: bash
        run: |
          echo ${{ matrix.include.group}}
