name: Testing Images
on:
   merge_group:
   pull_request:
     branches:
       - main
   workflow_call:
   workflow_dispatch:

jobs:
  build-image-testing:
    name: Build Testing Images
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      image_flavors: '["main", "nvidia-open"]'
      image_names: '["aurora", "aurora-dx"]'
      stream_name: "testing"
      architectures: '["amd64", "arm64"]'
