name: Testing Images
on:
  merge_group:
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  aurora:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      image_flavors: '["main"]'
      image_names: '["aurora"]'
      stream_name: "testing"
      architectures: '["amd64", "arm64"]'

  aurora-dx:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      image_flavors: '["main"]'
      image_names: '["aurora-dx"]'
      stream_name: "testing"
      architectures: '["amd64", "arm64"]'

  aurora-nvidia-open:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      image_flavors: '["nvidia-open"]'
      image_names: '["aurora"]'
      stream_name: "testing"
      architectures: '["amd64", "arm64"]'

  aurora-dx-nvidia-open:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      image_flavors: '["nvidia-open"]'
      image_names: '["aurora-dx"]'
      stream_name: "testing"
      architectures: '["amd64", "arm64"]'
